language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: ISukPgdtgvkx4Jb63A6p/gnkksQuURCcTzn6Wa9VEZoDlUFzEudruzU7XBeydIlk0LkQdW9mAtAf4by5BMJE2kXkRTsCy4RxqknKfD6jZOVhlupMP3asSqL+t1Nzd0QnZSMZsn7vWsQ16zGIwuS6GzXP2vO1F9Z8LYqgVjjvcLJBPYYNCzivn210a0wBwVzWZZShrRK9ynLZMzBuSBfqHoJ85Q7UQSMg4gvpa51wS0fv2YCaeOvDoD0txkpg5xNCtpDXS2CicYoUR2FLtpAmFPsgh4nVFawcFRaMa8wz2HLKFvS486SQD4WnJL2aLdykeUQHAsQld3VkGxhr5Nl8nA1TqzMqxL3s1KnnvUTD0zwSXhs2wYComYmCPZ9T0CLLDNDlaVVqGMaR2xtqh7aUXqQCvKSyHU3wd1KoFxps5DWXT5/hkM4yhCYjiVFYXJaPMR7CC0qvnnv0Ohs01tA8wLeYSZjkYuEXmG6JzxZuEGg/KhBtJq/8LBPWbDMb0dTLXqKKQTaJvTT3y5EqMFkJy49QAUIc1jaB8NqM/xpaC1y37Mf2z56IHBbJ98b8hw95EZBAer47zacvVRr8cOoOQfI94TTEgCCm04rUZLX/SVVkz+2Mg9c6yrkH5gelOBNiLSmRe88yJk2AW9uA7+nxhOhca6Uzg4D/WrTBE6gPJbU=
  app: secret-tundra-70896
  on:
    repo: gdalporto/MLC-band
